name: Build

on:
    workflow_dispatch:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - labeled

jobs:
    build:
        uses: NordicSemiconductor/pc-nrfconnect-shared/.github/workflows/build-app.yml@push-zlwuyylnnpqv
